Does going to university in a different country affect your mental health? A Japanese international university surveyed its students in 2018 and published a study the following year that was approved by several ethical and regulatory boards.

The study found that international students have a higher risk of mental health difficulties than the general population. 


I will Explore the `students` data using PostgreSQL to find out if I would come to a similar conclusion for international students and see if the length of stay is a contributing factor.

Here is an overview of the dataset:

| Field Name    | Description                                      |
| ------------- | ------------------------------------------------ |
| `inter_dom`     | Types of students (international or domestic)   |
| `japanese_cate` | Japanese language proficiency                    |
| `english_cate`  | English language proficiency                     |
| `academic`      | Current academic level (undergraduate or graduate) |
| `age`           | Current age of student                           |
| `stay`          | Current length of stay in years                  |
| `todep`         | Total score of depression (PHQ-9 test)           |
| `tosc`          | Total score of social connectedness (SCS test)   |
| `toas`          | Total score of acculturative stress (ASISS test) |

In [1]:
-- Run this code to view the data in st
SELECT COUNT(*) AS count_dom,	
	   ROUND(AVG(todep), 2) AS average_depression_sc, 
       ROUND(AVG(tosc), 2) AS average_social_sc, 
       ROUND(AVG(toas), 2) AS average_stress_sc
FROM students
WHERE inter_dom = 'Dom'

   count_dom  average_depression_sc  average_social_sc  average_stress_sc
0         67                   8.61              37.64              62.84

In [2]:
-- Find the number of international students and their average stress scores by length of stay, in descending order of length of stay
SELECT COUNT(*) AS count_int,
       ROUND(AVG(todep), 2) AS average_depression_sc, 
       ROUND(AVG(tosc), 2) AS average_social_sc, 
       ROUND(AVG(toas), 2) AS average_stress_sc
FROM students
WHERE inter_dom = 'Inter'

   count_int  average_depression_sc  average_social_sc  average_stress_sc
0        201                   8.04              37.42              75.56